# 프로그램 실행 중 오류 처리

프로그램을 실행하는 동안 프로그램이 예기치 않게 비정상적으로 종료되는 다양한 상황이 발생할 수 있다.

```java
public class TestException {
    public static void main(String[] args) {
        int falseNumber = Integer.parseInt("OK");
        System.out.println("print");
    }
}
```

다음 메시지가 출력된다.
```java
Exception in thread "main" java.lang.NumberFormatException: For input string: "OK"
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
  at java.lang.Integer.parseInt(Integer.java:468)
  at java.lang.Integer.parseInt(Integer.java:518)
  at TestException.main(TestException.java:3)
```

Java에서는 런타임 시 발생하는 오류를 **예외(Exceptions)** 로 표시한다. 프로그램이 예기치 않게 종료되는 것을 방지하기 위해 Java에서는 적절한 구성을 통해 예외를 처리할 수 있다.