# 예외 전파

예외가 발생한 곳에서 예외가 포착되지 않고 처리되지 않으면 예외가 발생한 메서드를 호출한 메서드로 제어가 전달된다. 예외가 포착되거나 컨트롤이 프로그램을 종료하고 오류 메시지를 생성하는 `main` 메서드로 전달될 때까지 전파가 계속된다.

메서드 종료 체인을 시작하는 것은 `throw`문 이다.

```java
import java.io.*;

public class ExceptionPropagation1 {

    public static void main(String[] args) throws Exception {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        System.out.println("Insert a number:");
        int c = Integer.parseInt(br.readLine());
        first(c);
    }

    private static void first(int a) throws Exception {
        second(a);
    }

    private static void second(int b) throws Exception {
        Exception propagate = new Exception("The value is too small.");
        if (b < 10)
            throw propagate;
        System.out.println("OK");
    }
}
```